name: Deploy API (Development)

on:
  push:
    branches:
      - develop
    paths:
      - 'wedding-api/**'
defaults:
  run:
    working-directory: ./wedding-api
jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
  deploy:
    name: Deploy Dev API
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "cd wedding-api && serverless deploy --stage=dev --verbose"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGODB_URI: ${{ secrets.DEV_MONGODB_URI }}
