name: Deploy API (Development)

on:
  push:
    branches:
      - develop
    paths:
      - 'wedding-api/**'
defaults:
  run:
    working-directory: ./wedding-api
jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Save Code Linting Report JSON
        id: linting
        run: yarn lint:report
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'wedding-api/eslint_report.json'
          only-pr-files: false
      - name: Exit on error
        if: steps.linting.outcome != 'success'
        run: exit 1

  deploy:
    name: Deploy Dev API
    needs: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Print Working directory and Yarn Version
        run: pwd && yarn --version
      - name: Install and View Tree
        run: sudo apt-get install tree && tree -a -I 'node_modules|.git' -L 4
      - name: Install modules
        run: yarn
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "cd wedding-api && serverless deploy --stage=dev --verbose"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGODB_URI: ${{ secrets.DEV_MONGODB_URI }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          EVENT_ID: ${{ secrets.DEV_EVENT_ID }}
          CDN_DOMAIN_NAME: ${{ secrets.CDN_DOMAIN_NAME }}
          CLOUDFRONT_SIGNER_PUBLIC_KEY: ${{ secrets.CLOUDFRONT_SIGNER_PUBLIC_KEY }}
          CLOUDFRONT_SIGNER_PRIVATE_KEY: ${{ secrets.CLOUDFRONT_SIGNER_PRIVATE_KEY }}
