name: Expo Publish
on:
  push:
    branches:
      - develop
    paths:
    - 'mobile-client/**'
jobs:
  publish:
    name: Publish Dev Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
      - run: yarn install
      - run: expo publish
