name: Lint Repository on PR
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
    paths:
      - 'mobile-client/**'
      - 'wedding-api/**'

jobs:
  lint:
    name: Lint Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn && cd mobile-client && yarn
      - name: Generate Linting Reports
        run: yarn lint:reports
        continue-on-error: true
      - name: Combine reports
        run: jq -s 'map(.[])' mobile-client/eslint_report.json wedding-api/eslint_report.json > eslint_report.json
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'eslint_report.json'
          only-pr-files: false
