name: Lint Mobile Client on PR
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
    paths:
      - 'mobile-client/**'
jobs:
  lint:
    name: Lint Mobile Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change Directory
        run: cd mobile-client
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: error
          github_token: ${{ secrets.GH_TOKEN }}
          eslint_flags: './'
          fail_on_error: true
