name: Lint API on PR
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
    paths:
      - 'wedding-api/**'
defaults:
  run:
    working-directory: ./wedding-api
jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: error
          github_token: ${{ secrets.GH_TOKEN }}
