name: Lint Mobile Client on PR
on:
  pull_request:
    branches:
      - develop
      - staging
      - production
    paths:
      - 'mobile-client/**'
defaults:
  run:
    working-directory: ./mobile-client
jobs:
  lint:
    name: Lint Mobile Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: './'
          workdir: ./mobile-client
